name: Vérification du numéro de version du plugin Moodle
on: [push]

jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:

      - name: Retrieve changes
        id: changes
        run: |
          git fetch --no-tags --depth=1 origin "+refs/heads/*:refs/remotes/origin/*"
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Extraire le numéro de version
        id: extract_version
        run: |
          VERSION=$(grep -oP '(\$plugin->version\s*=\s*['"'"'][^'"'"']+['"'"']\s*;)' ${{ steps.changes.outputs.changed_files }} | grep -oP '(\d+\.\d+\.\d+)')
          
          echo "::set-output name=version::$VERSION"

      - name: Vérifier l'incrémentation du numéro de version
        id: check_increment
        run: |
          PREVIOUS_VERSION=$(git show HEAD^:${{ steps.changes.outputs.changed_files }} | grep -oP '(\$plugin->version\s*=\s*['"'"'][^'"'"']+['"'"']\s*;)' | grep -oP '(\d+\.\d+\.\d+)')
          CURRENT_VERSION=${{ steps.extract_version.outputs.version }}
          
          if [ "$PREVIOUS_VERSION" = "$CURRENT_VERSION" ]; then
            echo "Le numéro de version n'a pas été incrémenté."
            exit 1
          fi
          
          echo "Le numéro de version a été incrémenté."

      - name: Envoyer une notification
        if: ${{ failure() }}
        run: |
          echo "Le numéro de version du plugin Moodle n'a pas été incrémenté. Veuillez vérifier et mettre à jour le numéro de version approprié."
