name: Vérification du numéro de version du plugin Moodle
on: [push, workflow_dispatch]

jobs:
  getVersions:
    runs-on: ubuntu-latest
    outputs:
      old_version: ${{ steps.extract_old_version.outputs.old_version }}
      new_version: ${{ steps.extract_new_version.outputs.new_version }}

    steps:

      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            version.php
          sparse-checkout-cone-mode: false

      - name: "Extract new version number"
        id: extract_new_version
        run: |
          VERSION= cat $GITHUB_WORKSPACE/version.php | grep version | grep -o -E '[0-9]{10}'
          echo $VERSION
          echo "new_version=${VERSION}" >> $GITHUB_OUTPUT

      - name: "Get git tree"
        id: get_git_tree
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: "Extract old version number"
        id: extract_old_version
        run: |
          git checkout HEAD^
          VERSION= cat $GITHUB_WORKSPACE/version.php | grep version | grep -o -E '[0-9]{10}'
          echo $VERSION
          echo "old_version=$VERSION" >> $GITHUB_OUTPUT

  compare-versions:
    runs-on: ubuntu-latest
    needs: getVersions
    steps:
      - name: "Compare versions"
        env:
          NEW_VERSION: ${{needs.getVersions.outputs.new_version}}
          OLD_VERSION: ${{needs.getVersions.outputs.old_version}}
        run: |
          echo "$OLD_VERSION -> $NEW_VERSION"
          if [ $((OLD_VERSION)) < $((NEW_VERSION)) ]; then
            echo "Le numéro de version a été incrémenté."
            exit 0
          fi
          echo "Le numéro de version n'a pas été incrémenté."
          exit 1

      - name: "Send notification"
        if: ${{ failure() }}
        run: |
          echo "Le numéro de version du plugin Moodle n'a pas été incrémenté. Veuillez vérifier et mettre à jour le numéro de version approprié."
