name: Vérification du numéro de version du plugin Moodle
on: [push]

jobs:
  check_version:
    runs-on: ubuntu-latest
    outputs:
      old_version: ${{ steps.extract_old_version.outputs.old_version }}
      new_version: ${{ steps.extract_new_version.outputs.new_version }}

    steps:

      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            version.php
          sparse-checkout-cone-mode: false

      - name: Extract new version number
        id: extract_new_version
        run: |
          VERSION= cat $GITHUB_WORKSPACE/version.php | grep version | grep -o -E '[0-9]{10}'
          echo $VERSION
          echo "new_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Extract old version number
        id: extract_old_version
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: |
          git checkout HEAD^
          VERSION= cat $GITHUB_WORKSPACE/version.php | grep version | grep -o -E '[0-9]{10}'
          echo $VERSION
          echo "old_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare_version
        run: |
          if [ ${{ steps.extract_old_version.outputs.old_version }} < ${{ steps.extract_new_version.outputs.new_version }} ]; then
            echo "Le numéro de version a été incrémenté."
            exit 0
          fi
          echo "Le numéro de version n'a pas été incrémenté."
          exit 1

      - name: Envoyer une notification
        if: ${{ failure() }}
        run: |
          echo "Le numéro de version du plugin Moodle n'a pas été incrémenté. Veuillez vérifier et mettre à jour le numéro de version approprié."
